### ISSUE TITLE
Umbrella issue for plugin_test

### ISSUE THREAD

**Issue by imbsky** [asdf-community/.github#2]
Add `plugin_test` job for community plugins.

```yml
plugin_test:
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest]

  runs-on: ${{ matrix.os }}

  steps:
    - name: asdf_plugin_test
      uses: asdf-vm/actions/plugin-test@v1.0.0
      with:
        command: COMMAND --version
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/asdf-community/asdf-direnv/blob/master/.github/workflows/workflow.yml

- [x] [asdf-alp](https://github.com/asdf-community/asdf-alp) - @Naturalclar
- [x] [asdf-ccache](https://github.com/asdf-community/asdf-ccache) - @sasurau4
- [x] [asdf-deno](https://github.com/asdf-community/asdf-deno) - @sasurau4
- [x] [asdf-elm](https://github.com/asdf-community/asdf-elm) - @Haritaso
- [x] [asdf-fstar](https://github.com/asdf-community/asdf-fstar) - @Naturalclar
- [x] [asdf-lean](https://github.com/asdf-community/asdf-lean) - @sasurau4
- [x] [asdf-mlton](https://github.com/asdf-community/asdf-mlton) - @sasurau4
- [x] [asdf-ocaml](https://github.com/asdf-community/asdf-ocaml) - @nzws
- [x] [asdf-rlwrap](https://github.com/asdf-community/asdf-rlwrap) - @sasurau4
- [x] [asdf-zen](https://github.com/asdf-community/asdf-zen) - @imbsky
- [x] [asdf-aria2](https://github.com/asdf-community/asdf-aria2) - @sasurau4
- [x] [asdf-cue](https://github.com/asdf-community/asdf-cue) - @Naturalclar
- [x] [asdf-direnv](https://github.com/asdf-community/asdf-direnv) - @vic
- [x] [asdf-esy](https://github.com/asdf-community/asdf-esy) - @Naturalclar
- [x] [asdf-haxe](https://github.com/asdf-community/asdf-haxe) - @imbsky
- [x] [asdf-meson](https://github.com/asdf-community/asdf-meson) - @Naturalclar
- [x] [asdf-ninja](https://github.com/asdf-community/asdf-ninja) - @jeffryang24
- [x] [asdf-opam](https://github.com/asdf-community/asdf-opam) - @Naturalclar
- [x] [asdf-rust](https://github.com/asdf-community/asdf-rust) - @nesso-pfl

**Comment by Naturalclar** [comment]
I'll work on `asdf-alp`

**Comment by imbsky** [comment]
@Naturalclar Thank you!

**Comment by nzws** [comment]
Can I take `asdf-ocaml`?😊

**Comment by imbsky** [comment]
@nzws Sure!

**Comment by vic** [comment]
HAha, love you all people, keep asdf-community awesome!

**Comment by sasurau4** [comment]
I'll work on `asdf-deno`

**Comment by imbsky** [comment]
Thank you!

**Comment by imbsky** [comment]
Probably the test will fail due to an upstream bug, so don't worry about it if the test fails.

**Comment by Haritaso** [comment]
I'll work on `asdf-elm`

**Comment by imbsky** [comment]
@Haritaso Thank you!

**Comment by nesso-pfl** [comment]
Can I work on `asdf-rust`?

**Comment by imbsky** [comment]
Sure!

**Comment by imbsky** [comment]
The problem of test failure has been fixed in all repositories.

**Comment by imbsky** [comment]
We decided to replace the build step with the plugin_test step. There are still many repositories that need PR. Please feel free to help us.

**Comment by Naturalclar** [comment]
I'll take `asdf-esy`

**Comment by sasurau4** [comment]
I'll take `asdf-ccache`

**Comment by jeffryang24** [comment]
I'll take `asdf-ninja`. :bowing_man:

**Comment by imbsky** [comment]
@jeffryang24 Thank you!

**Comment by imbsky** [comment]
We welcome all contributions to this issue, whether you are a member or not. We don't have to update everything in a hurry, but the sooner, the better.

**Comment by Naturalclar** [comment]
I'll take `asdf-fstar`

**Comment by imbsky** [comment]
@Naturalclar Thank you! We are looking for one more maintainer recently. if you okay, I would like to invite you as a maintainer because I know you well.

**Comment by Naturalclar** [comment]
@imbsky sure! I can help 😄

**Comment by imbsky** [comment]
@Naturalclar Thanks! I sent you an invitation!

**Comment by Naturalclar** [comment]
I'll take `asdf-cue` and `asdf-meson`

**Comment by Naturalclar** [comment]
Checklist should be completed now :tada:

**Comment by imbsky** [comment]
Thanks to the many contributors, we were able to complete the CI configuration updates for all repositories!
